<?php
echo "<h1>Hola, mundo!</h1>";
echo "<p>Bienvenido a mi página web.</p>";
echo "<p>Esta es una prueba de PHP.</p>";
echo "<p>Espero que estés teniendo un buen día.</p>";
echo "<p>¡Gracias por visitar!</p>";
echo "<p>¡Hasta luego!</p>";
echo "<p>¡Adiós!</p>";
echo "<p>¡Nos vemos pronto!</p>";
echo "<p>¡Cuídate!</p>";
echo "<p>¡Saludos!</p>";
echo "<p>¡Un abrazo!</p>";
echo "<p>¡Que tengas un buen día!</p>";
echo "<p>¡Disfruta de tu tiempo!</p>";
echo "<p>¡Recuerda sonreír!</p>";
echo "<p>¡La vida es hermosa!</p>";
echo "<p>¡Aprovecha cada momento!</p>";
echo "<p>¡Haz lo que amas!</p>";
echo "<p>¡Sigue tus sueños!</p>";
echo "<p>¡Nunca te rindas!</p>";
echo "<p>¡Eres increíble!</p>";
echo "<p>¡Cree en ti mismo!</p>";
echo "<p>¡Todo es posible!</p>";
echo "<p>¡La felicidad está en ti!</p>";
echo "<p>¡Disfruta del viaje!</p>";
echo "<p>¡Hazlo con pasión!</p>";
echo "<p>¡Sé agradecido!</p>";
echo "<p>¡Valora lo que tienes!</p>";
echo "<p>¡Aprende algo nuevo cada día!</p>";
echo "<p>¡Sé amable con los demás!</p>";
echo "<p>¡La bondad siempre regresa!</p>";
echo "<p>¡Sonríe a la vida!</p>";
echo "<p>¡La vida es un regalo!</p>";
echo "<p>¡Aprovecha cada día!</p>";
echo "<p>¡Haz que cuente!</p>";
echo "<p>¡Sé feliz!</p>";
echo "<p>¡Vive el momento!</p>";
echo "<p>¡Crea recuerdos!</p>";
echo "<p>¡Disfruta de las pequeñas cosas!</p>";
echo "<p>¡La felicidad está en los detalles!</p>";
echo "<p>¡Sé tú mismo!</p>";
echo "<p>¡No te compares con los demás!</p>";
echo "<p>¡Eres único!</p>";
echo "<p>¡Celebra tus logros!</p>"; 
echo "<p>¡No importa cuán pequeños sean!</p>";
echo "<p>¡Cada paso cuenta!</p>";
echo "<p>¡Sigue adelante!</p>";
echo "<p>¡No mires atrás!</p>";
echo "<p>¡El futuro es brillante!</p>";
echo "<p>¡Cree en tus capacidades!</p>";
?>